### ISSUE TITLE
Полупрозрачные элементы ломают всю вёрстку

### ISSUE THREAD

**Issue by MelonHell** [Brikster/glyphs#5]
Не знаю в глифсе ли проблема или в майнкрафте, но я полагаю, что даже если проблема в майне, то на стороне глифса можно правильно обработать данное поведение

Обычное поведение:
![image](https://user-images.githubusercontent.com/53826469/228965765-6c134a2a-d540-4022-a729-d417ce6464ec.png)

Полупрозрачный фон у title:
![image](https://user-images.githubusercontent.com/53826469/228965616-f260a1cc-382e-42af-8ae2-644eab2fb3d9.png)

**Comment by MelonHell** [comment]
Если я правильно понял, то глифс предполагает что ширина элемента равна его реальной ширине, но на стороне майна его ширина нулёвая, в таком случае как костыль, можно просто заполнить пространство под элементом пробелами

**Comment by Brikster** [comment]
Там какая-то не совсем очевидная логика с (полу-)прозрачными пикселями. В текущем варианте, по крайней мере, корректно обрабатывается ширина букв для шрифтов (с этим при разработке было много проблем). Есть одна идея, которая может помочь - в dev-ветку запушил и задеплоил снапшот.

**Comment by MelonHell** [comment]
> Там какая-то не совсем очевидная логика с (полу-)прозрачными пикселями. В текущем варианте, по крайней мере, корректно обрабатывается ширина букв для шрифтов (с этим при разработке было много проблем). Есть одна идея, которая может помочь - в dev-ветку запушил и задеплоил снапшот.

вроде теперь всё правльно, спасибо

![image](https://user-images.githubusercontent.com/53826469/228971750-6bfbf5fc-527e-418a-a993-350fef31d415.png)
